// config.h — generated by extras/dashboard.html (this is the default; replace with your own).
//
// A dashboard is a list of WIDGETS. Each one owns a bounding box {x,y,w,h} and a `fast` flag:
// when its content changes, a `fast` widget is redrawn with the panel's ~0.4 s partial refresh
// (just its box); a non-fast widget waits for the periodic full refresh. Design fast-changing
// things (clocks, live values, bars) as fast=true and static chrome as fast=false.
//
// `source` is "scheme:arg" and is the extension point — add your own schemes in Dashboard.ino:
//   static:TEXT        a fixed string            clock:%H:%M    NTP time (strftime)
//   lhm:Sensor Name    LibreHardwareMonitor      batt           battery %
//   lhm:Name:%         ...disambiguated by unit  temp / hum     on-board SHT4x
//   json:key           a field from CFG_DATA_URL  (your own server / Home Assistant)
#pragma once
#include <stdint.h>

#define CFG_WIFI_SSID  "your-ssid"
#define CFG_WIFI_PASS  "your-password"
#define CFG_DATA_URL   "http://192.168.1.50:8085/data.json"   // primary JSON for lhm:/json: ("" = none)
#define CFG_REFRESH_S  2
#define CFG_FULL_EVERY 60                                      // force a full refresh every N ticks

enum { W_BOX, W_BAR, W_VALUE, W_TEXT, W_BLOCK, W_QR };

// type, x, y, w, h, fast, source, fmt, size
//   VALUE fmt = printf for one float (e.g. "%.1f C");  BAR fmt = "min:max";  TEXT/BLOCK fmt = suffix
struct Widget { uint8_t type; int16_t x, y, w, h; bool fast;
                const char* source; const char* fmt; uint8_t size; };

static const Widget CFG_WIDGETS[] = {
  { W_TEXT,   24,  16, 560,  30, false, "static:reTerminal Dashboard", "",       3 },
  { W_QR,    632,  10, 158, 158, false, "static:https://github.com/Toastee0/Seeed_E100X_LibSaltee", "", 0 },
  { W_TEXT,   44,  88, 200,  20, false, "static:CPU",           "",        2 },
  { W_VALUE,  44, 110, 320,  90, true,  "lhm:CPU Package",      "%.0f C",  8 },
  { W_BAR,    44, 210, 420,  30, true,  "lhm:CPU Total",        "0:100",   0 },
  { W_TEXT,   44, 258, 200,  20, false, "static:GPU",           "",        2 },
  { W_VALUE,  44, 280, 320,  90, true,  "lhm:GPU Core",         "%.0f C",  8 },
  { W_BAR,    44, 380, 420,  30, true,  "lhm:GPU Core:%",       "0:100",   0 },
  { W_TEXT,  500, 300, 290,  30, true,  "clock:%H:%M:%S",       "",        3 },
  { W_VALUE, 500, 360, 290,  30, true,  "batt",                 "batt %.0f%%", 3 },
};
static const int CFG_WIDGET_COUNT = sizeof(CFG_WIDGETS) / sizeof(CFG_WIDGETS[0]);
