// config.h — generated by extras/setup.html (this is the default; replace it with your own).
//
// Open extras/setup.html in a browser, paste your LibreHardwareMonitor /data.json, tick the
// sensors you want and place them, then download a config.h and drop it in this folder. No C
// editing — the GUI writes everything below.
#pragma once
#include <stdint.h>

#define CFG_WIFI_SSID  "your-ssid"
#define CFG_WIFI_PASS  "your-password"
#define CFG_SOURCE_URL "http://192.168.1.50:8085/data.json"   // <pc-ip>:8085
#define CFG_REFRESH_S  5

// One row per value to show. `sensor` is the exact LibreHardwareMonitor "Text"; `unit` is the
// character that identifies which same-named sensor you mean (C=temperature, %=load, W=power,
// M=MHz clock) and is appended after the number; x/y is the top-left; size is the Adafruit_GFX
// text size for the value (label is drawn smaller just above it).
struct CfgItem { const char* sensor; const char* label; int16_t x, y; uint8_t size; const char* unit; };

static const CfgItem CFG_ITEMS[] = {
  { "CPU Package", "CPU", 40,  150, 8, "C" },
  { "GPU Core",    "GPU", 430, 150, 8, "C" },
  { "CPU Total",   "CPU load", 40,  320, 4, "%" },
  { "GPU Core",    "GPU load", 430, 320, 4, "%" },
};
static const int CFG_ITEM_COUNT = sizeof(CFG_ITEMS) / sizeof(CFG_ITEMS[0]);
